### PR TITLE
Mauritius test case with postcode

### PR DESCRIPTION
**Pull request by machajdik**
Removed post code 230 in original test. it seems like this is not a valid post code but rather a trick that Mauritians used before 2014 (https://yashvinblogs.com/2012/02/08/postal-code-zip-mauritius)

### CODE REVIEW

**Comment by machajdik** [comment]
Sorry for creating 2 different pull requests.

**Comment by freyfogle** [comment]
yes, in future one PR please. Also, this test fails. 
Your change to the template would not print the neighbourhood.

I appreciate the fix, so this time I will sort it all out, but please in future all of it in one PR, and with a passing test.

**Comment by freyfogle** [comment]
yes, in future one PR please. Also, this test fails. 
Your change to the template would not print the neighbourhood.

I appreciate the fix, so this time I will sort it all out, but please in future all of it in one PR, and with a passing test.

**Comment by freyfogle** [comment]
solved in https://github.com/OpenCageData/address-formatting/commit/e445b5537fa0ac7c806d430ca63efd77c1810d82 thus closing this PR

**Pull request closed without merging**
